using Shared.Entities.BaseEntity;
using SRSS.IAM.Repositories.Entities.Enums;

namespace SRSS.IAM.Repositories.Entities
{
    /// <summary>
    /// Stores the evaluation results generated by AI for a study selection process
    /// </summary>
    public class StudySelectionAIResult : BaseEntity<Guid>
    {
        public Guid StudySelectionProcessId { get; set; }
        public Guid PaperId { get; set; }
        public Guid ReviewerId { get; set; }
        public ScreeningPhase Phase { get; set; }
        public string AIOutputJson { get; set; } = null!;
        public double RelevanceScore { get; set; }
        public StuSeAIRecommendation Recommendation { get; set; }

        // Navigation Properties
        public StudySelectionProcess StudySelectionProcess { get; set; } = null!;
        public Paper Paper { get; set; } = null!;
        public User Reviewer { get; set; } = null!;
    }
}
