// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRSS.IAM.Repositories;

#nullable disable

namespace SRSS.IAM.Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211152350_TestCheckSchema")]
    partial class TestCheckSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.BibliographicDatabase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("BibliographicDatabases");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.CommissioningDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .HasColumnType("text");

                    b.Property<string>("Sponsor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("CommissioningDocuments");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.Comparison", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("comparison_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PicocId")
                        .HasColumnType("uuid")
                        .HasColumnName("picoc_id");

                    b.HasKey("Id");

                    b.HasIndex("PicocId")
                        .IsUnique();

                    b.ToTable("comparison", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ConferenceProceeding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("ConferenceProceedings");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.Context", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("context_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Environment")
                        .HasColumnType("text")
                        .HasColumnName("environment");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PicocId")
                        .HasColumnType("uuid")
                        .HasColumnName("picoc_id");

                    b.HasKey("Id");

                    b.HasIndex("PicocId")
                        .IsUnique();

                    b.ToTable("context", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.DigitalLibrary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("DigitalLibraries");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ExclusionCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriteriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaId");

                    b.ToTable("ExclusionCriteria");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.InclusionCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriteriaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaId");

                    b.ToTable("InclusionCriteria");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.Intervention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("intervention_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PicocId")
                        .HasColumnType("uuid")
                        .HasColumnName("picoc_id");

                    b.HasKey("Id");

                    b.HasIndex("PicocId")
                        .IsUnique();

                    b.ToTable("intervention", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.Journal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.Outcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outcome_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Metric")
                        .HasColumnType("text")
                        .HasColumnName("metric");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PicocId")
                        .HasColumnType("uuid")
                        .HasColumnName("picoc_id");

                    b.HasKey("Id");

                    b.HasIndex("PicocId")
                        .IsUnique();

                    b.ToTable("outcome", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.PicocElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("picoc_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("element_type");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResearchQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("research_question_id");

                    b.HasKey("Id");

                    b.HasIndex("ResearchQuestionId");

                    b.ToTable("picoc_element", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.Population", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("population_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PicocId")
                        .HasColumnType("uuid")
                        .HasColumnName("picoc_id");

                    b.HasKey("Id");

                    b.HasIndex("PicocId")
                        .IsUnique();

                    b.ToTable("population", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ProtocolEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvaluationResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReviewerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("ProtocolEvaluations");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ProtocolReviewer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Affiliation")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProtocolReviewers");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ProtocolVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uuid");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolId");

                    b.ToTable("ProtocolVersions");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.QuestionType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuestionTypes");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ResearchQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("research_question_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<Guid>("QuestionTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_type_id");

                    b.Property<string>("Rationale")
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("QuestionTypeId");

                    b.ToTable("research_question", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ReviewNeed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("Justification")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ReviewNeeds");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ReviewObjective", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObjectiveStatement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ReviewObjectives");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ReviewProtocol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("protocol_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ProtocolVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("protocol_version");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("review_protocol", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolId");

                    b.ToTable("SearchSources");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchStrategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("strategy_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uuid")
                        .HasColumnName("protocol_id");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolId");

                    b.ToTable("search_strategy", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchString", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StrategyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StrategyId");

                    b.ToTable("SearchStrings");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchStringTerm", b =>
                {
                    b.Property<Guid>("SearchStringId")
                        .HasColumnType("uuid")
                        .HasColumnName("search_string_id");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uuid")
                        .HasColumnName("term_id");

                    b.HasKey("SearchStringId", "TermId");

                    b.HasIndex("TermId");

                    b.ToTable("search_string_term", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SearchTerms");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.StudySelectionCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProtocolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolId");

                    b.ToTable("StudySelectionCriterias");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SystematicReviewProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("project_id")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Domain")
                        .HasColumnType("text")
                        .HasColumnName("domain");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("systematic_review_project", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRefreshTokenRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_refresh_token_revoked");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_is_active");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.BibliographicDatabase", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.SearchSource", "Source")
                        .WithOne("BibliographicDatabase")
                        .HasForeignKey("SRSS.IAM.Repositories.Entities.BibliographicDatabase", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.CommissioningDocument", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.SystematicReviewProject", "Project")
                        .WithMany("CommissioningDocuments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.Comparison", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.PicocElement", "PicocElement")
                        .WithOne("Comparison")
                        .HasForeignKey("SRSS.IAM.Repositories.Entities.Comparison", "PicocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PicocElement");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ConferenceProceeding", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.SearchSource", "Source")
                        .WithOne("ConferenceProceeding")
                        .HasForeignKey("SRSS.IAM.Repositories.Entities.ConferenceProceeding", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.Context", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.PicocElement", "PicocElement")
                        .WithOne("Context")
                        .HasForeignKey("SRSS.IAM.Repositories.Entities.Context", "PicocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PicocElement");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.DigitalLibrary", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.SearchSource", "Source")
                        .WithOne("DigitalLibrary")
                        .HasForeignKey("SRSS.IAM.Repositories.Entities.DigitalLibrary", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ExclusionCriterion", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.StudySelectionCriteria", "Criteria")
                        .WithMany("ExclusionCriteria")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.InclusionCriterion", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.StudySelectionCriteria", "Criteria")
                        .WithMany("InclusionCriteria")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.Intervention", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.PicocElement", "PicocElement")
                        .WithOne("Intervention")
                        .HasForeignKey("SRSS.IAM.Repositories.Entities.Intervention", "PicocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PicocElement");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.Journal", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.SearchSource", "Source")
                        .WithOne("Journal")
                        .HasForeignKey("SRSS.IAM.Repositories.Entities.Journal", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.Outcome", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.PicocElement", "PicocElement")
                        .WithOne("Outcome")
                        .HasForeignKey("SRSS.IAM.Repositories.Entities.Outcome", "PicocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PicocElement");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.PicocElement", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.ResearchQuestion", "ResearchQuestion")
                        .WithMany("PicocElements")
                        .HasForeignKey("ResearchQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchQuestion");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.Population", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.PicocElement", "PicocElement")
                        .WithOne("Population")
                        .HasForeignKey("SRSS.IAM.Repositories.Entities.Population", "PicocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PicocElement");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ProtocolEvaluation", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.ReviewProtocol", "Protocol")
                        .WithMany("Evaluations")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRSS.IAM.Repositories.Entities.ProtocolReviewer", "Reviewer")
                        .WithMany("Evaluations")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protocol");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ProtocolVersion", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.ReviewProtocol", "Protocol")
                        .WithMany("Versions")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ResearchQuestion", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.SystematicReviewProject", "Project")
                        .WithMany("ResearchQuestions")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRSS.IAM.Repositories.Entities.QuestionType", "QuestionType")
                        .WithMany("ResearchQuestions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("QuestionType");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ReviewNeed", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.SystematicReviewProject", "Project")
                        .WithMany("ReviewNeeds")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ReviewObjective", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.SystematicReviewProject", "Project")
                        .WithMany("ReviewObjectives")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ReviewProtocol", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.SystematicReviewProject", "Project")
                        .WithMany("Protocols")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchSource", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.ReviewProtocol", "Protocol")
                        .WithMany("SearchSources")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchStrategy", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.ReviewProtocol", "Protocol")
                        .WithMany("SearchStrategies")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchString", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.SearchStrategy", "Strategy")
                        .WithMany("SearchStrings")
                        .HasForeignKey("StrategyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Strategy");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchStringTerm", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.SearchString", "SearchString")
                        .WithMany("SearchStringTerms")
                        .HasForeignKey("SearchStringId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SRSS.IAM.Repositories.Entities.SearchTerm", "SearchTerm")
                        .WithMany("SearchStringTerms")
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchString");

                    b.Navigation("SearchTerm");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.StudySelectionCriteria", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.ReviewProtocol", "Protocol")
                        .WithMany("SelectionCriterias")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.PicocElement", b =>
                {
                    b.Navigation("Comparison");

                    b.Navigation("Context");

                    b.Navigation("Intervention");

                    b.Navigation("Outcome");

                    b.Navigation("Population");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ProtocolReviewer", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.QuestionType", b =>
                {
                    b.Navigation("ResearchQuestions");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ResearchQuestion", b =>
                {
                    b.Navigation("PicocElements");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ReviewProtocol", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("SearchSources");

                    b.Navigation("SearchStrategies");

                    b.Navigation("SelectionCriterias");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchSource", b =>
                {
                    b.Navigation("BibliographicDatabase");

                    b.Navigation("ConferenceProceeding");

                    b.Navigation("DigitalLibrary");

                    b.Navigation("Journal");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchStrategy", b =>
                {
                    b.Navigation("SearchStrings");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchString", b =>
                {
                    b.Navigation("SearchStringTerms");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchTerm", b =>
                {
                    b.Navigation("SearchStringTerms");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.StudySelectionCriteria", b =>
                {
                    b.Navigation("ExclusionCriteria");

                    b.Navigation("InclusionCriteria");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SystematicReviewProject", b =>
                {
                    b.Navigation("CommissioningDocuments");

                    b.Navigation("Protocols");

                    b.Navigation("ResearchQuestions");

                    b.Navigation("ReviewNeeds");

                    b.Navigation("ReviewObjectives");
                });
#pragma warning restore 612, 618
        }
    }
}
