// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SRSS.IAM.Repositories;

#nullable disable

namespace SRSS.IAM.Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260212072007_project-papers")]
    partial class projectpapers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.IdentificationProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("ReviewProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_process_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ReviewProcessId");

                    b.ToTable("identification_processes", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("ImportedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("imported_by");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid?>("SearchExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("search_execution_id");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer")
                        .HasColumnName("total_records");

                    b.HasKey("Id");

                    b.HasIndex("SearchExecutionId");

                    b.ToTable("import_batches", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.Paper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abstract")
                        .HasColumnType("text")
                        .HasColumnName("abstract");

                    b.Property<string>("AbstractLanguage")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("abstract_language");

                    b.Property<string>("AccessType")
                        .HasColumnType("text")
                        .HasColumnName("access_type");

                    b.Property<string>("Authors")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("authors");

                    b.Property<string>("ConferenceCountry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("conference_country");

                    b.Property<DateTimeOffset?>("ConferenceEndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("conference_end_date");

                    b.Property<string>("ConferenceLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("conference_location");

                    b.Property<string>("ConferenceName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("conference_name");

                    b.Property<DateTimeOffset?>("ConferenceStartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("conference_start_date");

                    b.Property<int?>("ConferenceYear")
                        .HasColumnType("integer")
                        .HasColumnName("conference_year");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentSelectionStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_selection_status");

                    b.Property<string>("DOI")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("doi");

                    b.Property<bool?>("FullTextAvailable")
                        .HasColumnType("boolean")
                        .HasColumnName("full_text_available");

                    b.Property<Guid?>("ImportBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_batch_id");

                    b.Property<DateTimeOffset?>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<string>("ImportedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("imported_by");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("text")
                        .HasColumnName("internal_notes");

                    b.Property<bool>("IsIncludedFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_included_final");

                    b.Property<string>("Issue")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("issue");

                    b.Property<string>("Journal")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("journal");

                    b.Property<string>("JournalEIssn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("journal_e_issn");

                    b.Property<string>("JournalIssn")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("journal_issn");

                    b.Property<string>("JournalPublisher")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("journal_publisher");

                    b.Property<string>("Keywords")
                        .HasColumnType("text")
                        .HasColumnName("keywords");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("language");

                    b.Property<DateTimeOffset?>("LastDecisionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_decision_at");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Pages")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pages");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pdf_url");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("PublicationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publication_date");

                    b.Property<string>("PublicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("publication_type");

                    b.Property<string>("PublicationYear")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("publication_year");

                    b.Property<int?>("PublicationYearInt")
                        .HasColumnType("integer")
                        .HasColumnName("publication_year_int");

                    b.Property<string>("Publisher")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("publisher");

                    b.Property<string>("RawReference")
                        .HasColumnType("text")
                        .HasColumnName("raw_reference");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_record_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.Property<string>("Volume")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("volume");

                    b.HasKey("Id");

                    b.HasIndex("DOI");

                    b.HasIndex("ImportBatchId");

                    b.HasIndex("ProjectId");

                    b.ToTable("papers", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ReviewProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("current_phase");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("idx_review_process_project_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_review_process_status");

                    b.ToTable("review_processes", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<Guid>("IdentificationProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("identification_process_id");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int>("ResultCount")
                        .HasColumnType("integer")
                        .HasColumnName("result_count");

                    b.Property<string>("SearchQuery")
                        .HasColumnType("text")
                        .HasColumnName("search_query");

                    b.Property<string>("SearchSource")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("search_source");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("IdentificationProcessId");

                    b.ToTable("search_executions", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SystematicReviewProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Domain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("domain");

                    b.Property<DateTimeOffset?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_project_status");

                    b.HasIndex("Title")
                        .HasDatabaseName("idx_project_title");

                    b.ToTable("systematic_review_projects", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRefreshTokenRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_refresh_token_revoked");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Password")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTimeOffset?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_users_is_active");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.IdentificationProcess", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.ReviewProcess", "ReviewProcess")
                        .WithMany("IdentificationProcesses")
                        .HasForeignKey("ReviewProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReviewProcess");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ImportBatch", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.SearchExecution", "SearchExecution")
                        .WithMany("ImportBatches")
                        .HasForeignKey("SearchExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SearchExecution");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.Paper", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.ImportBatch", "ImportBatch")
                        .WithMany("Papers")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SRSS.IAM.Repositories.Entities.SystematicReviewProject", "Project")
                        .WithMany("Papers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ReviewProcess", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.SystematicReviewProject", "Project")
                        .WithMany("ReviewProcesses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchExecution", b =>
                {
                    b.HasOne("SRSS.IAM.Repositories.Entities.IdentificationProcess", "IdentificationProcess")
                        .WithMany("SearchExecutions")
                        .HasForeignKey("IdentificationProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentificationProcess");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.IdentificationProcess", b =>
                {
                    b.Navigation("SearchExecutions");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ImportBatch", b =>
                {
                    b.Navigation("Papers");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.ReviewProcess", b =>
                {
                    b.Navigation("IdentificationProcesses");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SearchExecution", b =>
                {
                    b.Navigation("ImportBatches");
                });

            modelBuilder.Entity("SRSS.IAM.Repositories.Entities.SystematicReviewProject", b =>
                {
                    b.Navigation("Papers");

                    b.Navigation("ReviewProcesses");
                });
#pragma warning restore 612, 618
        }
    }
}
